server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location /admin/ {
        try_files $uri $uri/ /admin/index.html;
    }

    location = /admin {
        return 301 /admin/;
    }

    location / {
        return 301 /admin/;
    }
}
